name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "510ff452a7f62ab80a3dbca0ab1707b106713e6b2a6f6f9cf0f4765cc9d3433f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
