name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1367efa3a3f704f32feee8514c9c93e6b002984cb6d090d221183130b09c47b3"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
