name = "OneClient 1.21.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.1-fabric"
update-url = "oneclient/generated/utility-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "afe31fe7e088af99ee4ec5e3528c0925640129d8254fb4df62e69cd4a9f8fc46"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
