name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "77b7609485ed59778066ae48a005b016e9d3c878f0218df3eb1a82b2dbc86f73"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
