name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9001c7d404a91128844b364faac5c390c2b60dbf7fabf3084cf4a70f38ac9d32"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
