name = "OneClient 1.21.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.1-fabric"
update-url = "oneclient/generated/performance-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "55cbf848cc67e3f1b8a070b07ecbbe6a1052368d0b2fee117e16e8b95466fb85"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
