name = "OneClient 26.2 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.2-fabric"
update-url = "oneclient/generated/hud-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51ab336dfbb663e9d3e2306d8127656c8b975bc98cd331de6d228df100a9ef05"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
