name = "OneClient 26.2 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.2-fabric"
update-url = "oneclient/generated/hud-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cc99daaac8b0489bcd3f21ef96cb751eb93ed30d923d9cbff5da45ebd05ed843"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
