name = "OneClient 26.2 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.2-fabric"
update-url = "oneclient/generated/hud-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "09f032a03bec09435f0199a5626c82dcc75c3959f6afed2c6a9a3aa71fc74ddb"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
