name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "728f7293c98361f938e1b1bd1058d8bd29a7e59f786411db1bc469b5523ccc7f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
