name = "OneClient 1.21.11 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.11-fabric"
update-url = "oneclient/generated/skyblock-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d05517143337e5f05f638c131f9143af8d30e4f575bd5679c3c3b19c76f032ea"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
