name = "OneClient 26.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.1-fabric"
update-url = "oneclient/generated/performance-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5deca90226ce17d46895a74bdbd05d93f3c877c8049c92e04690a8d80ad0de3b"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
