name = "OneClient 26.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.1-fabric"
update-url = "oneclient/generated/performance-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9fabc850da423dde6b354e8bfa77ed83f4f3848847d2bc0489d1c68d210fc921"

[versions]
fabric = "0.19.3"
minecraft = "26.1"

[options]
acceptable-game-versions = []
