name = "OneClient 26.1 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.1-fabric"
update-url = "oneclient/generated/performance-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d30485fc7dbe85c9a43a387c51d6c4f623e065ea9075c8ddf7e8157c040c4b7a"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
