name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "85a44b607f2a17678148e1411d8f8fc2bebdec273ced6c02e61ec0d13297b897"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
