name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "729c75c0d5e2aaad56915361513ee17ac47aa3b2f36c4d8eadd6de80e3653154"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
