name = "OneClient 1.21.11 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.11-fabric"
update-url = "oneclient/generated/performance-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ae7c1c448319b5f9c6f4392565a13c2f831fd35aa485fc06fbd91f832610af56"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
