name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "aa5e9f4ac363d0f5838e1cde6894a96e9fe6cfbf836ac799ea19ba045dff4839"

[versions]
fabric = "0.19.3"
minecraft = "26.1"
