name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61c1e1dc3d72f3055b5bed4a511dc597dc83ab943d445ce7d6c82ce5dcf2801d"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
