name = "OneClient 26.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.1-fabric"
update-url = "oneclient/generated/pvp-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "37be788e5624c835a4931fc76538c2609e0a22d1cb0534bbc3a725e914500f6d"

[versions]
fabric = "0.18.5"
minecraft = "26.1"
