name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4ddf7ad119ef9f1bccd3e44fa41b5668c6677a5f8a4d211e531e911f46eb10d2"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
