name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44f0eb99e2f86a7bdec4d6437c079256ecff3747e5250a69dddbb48503016977"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
