name = "OneClient 1.21.10 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-1.21.10-fabric"
update-url = "oneclient/generated/skyblock-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9e9c8fc3a1c9aef3002cd9e69eb5ba6a588cb5cd987b036eed6bb47a2360677"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
