name = "OneClient 26.2 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.2-fabric"
update-url = "oneclient/generated/performance-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "63dce5d1de0ad5fd6644cb76eb8e547276ca0fcd6f2640525cc3bb043a698222"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
