name = "OneClient 26.2 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.2-fabric"
update-url = "oneclient/generated/performance-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "64cc77d52cf2a98260cf816902ed73009699f27ef4ce9eee87ab66ea501c3d0d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
