name = "OneClient 26.2 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-26.2-fabric"
update-url = "oneclient/generated/performance-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "efe4b837c6034dfc2190edd62dd4c44707ccefdcd1618d2cfaf2d2a5c4ed44fe"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
