name = "OneClient 26.2 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.2-fabric"
update-url = "oneclient/generated/qol-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ed4b8e544b4b83bd674d5880a5d4fd3f216c5ccb7beb0fb242e89224b18db0ac"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
