name = "OneClient 26.2 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.2-fabric"
update-url = "oneclient/generated/qol-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "688c4e79fd24f1e787187a9c839bb5f9f66a2587c9f253e131e5cea127b9e520"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
