name = "OneClient 26.2 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.2-fabric"
update-url = "oneclient/generated/qol-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "020c489307b29eb343550dcfa49425bd69ceabb36119b676d81806c85f156620"

[versions]
fabric = "0.19.3"
minecraft = "26.2"

[options]
acceptable-game-versions = []
