name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "606317cf6e1a699f88a4c2f51cd753a729791c6d265d2b67b4ca6452c72baf24"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
