name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d87b222a0ba59871229bb19423021debe053c0d1c2c4f04d2b7ec3fe00271ad6"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
