name = "OneClient 1.21.10 Fabric [Performance]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Performance"
id = "performance-1.21.10-fabric"
update-url = "oneclient/generated/performance-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "380fe4a54c554b37a40a38ff1db5921b72e6edb36ac085574ca910c296803edf"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
