name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4cf0378df67355b581fe187b3466d2d0c7c22959b7d343aed360a63850af8080"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
