name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1f49e57ff45702105d2b0b75c45bb3ae2c1d7aef583d26c3c1d7331419725568"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
