name = "OneClient 1.21.11 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.11-fabric"
update-url = "oneclient/generated/utility-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52114aa41deaaee6eb0d8e1de8e1b5e785025c0a52e7ced638dd2434be672e98"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
