name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "897bcb7a5908651c7674b348b30761e6316bd8a9f257e7bc714b2d8e1a90b989"

[versions]
fabric = "0.18.5"
minecraft = "1.21.11"
