name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "ea97c1fcd7d454ea8a0b2583933ced3323e45d49ddbd4a5fbab7f2df0c7d9d14"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
