name = "OneClient 1.21.11 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.11-fabric"
update-url = "oneclient/generated/pvp-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bbeb2b3f723c4729728c8c622b8637ac9bfd1ea603697195eca2a1b42411f521"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
