name = "OneClient 1.21.11 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.11-fabric"
update-url = "oneclient/generated/qol-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "541bcefab4fa8360f7c46d0a4b9f8cd9ec34f78bb491f07905a06674dd06d7f9"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"

[options]
acceptable-game-versions = []
