name = "OneClient 26.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.1-fabric"
update-url = "oneclient/generated/hud-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "52b7aa7c6c380e765f90233b2ecbe935aa69d5da45d6fae4541b17180f4f1f77"

[versions]
fabric = "0.19.3"
minecraft = "26.1"
