name = "OneClient 26.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-26.1-fabric"
update-url = "oneclient/generated/hud-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "021d511fa55166b21a4a98c448291e50f2ff0c1624541843b83cc359ed1b1599"

[versions]
fabric = "0.19.3"
minecraft = "26.1"
