name = "OneClient 26.2 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.2-fabric"
update-url = "oneclient/generated/utility-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "1e4d2606fcff24914d49ed6dfb0332b3ffab7be7e57ac901298370823c2dbd9d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
