name = "OneClient 26.2 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.2-fabric"
update-url = "oneclient/generated/utility-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c1b3e78534bca897efd3e4e440d5834c4c0c3d80502c61196286fda217a486d"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
