name = "OneClient 26.2 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.2-fabric"
update-url = "oneclient/generated/utility-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "99221b35f5f67f27aba3f08975485472a1dbfcf3ff5dfd29429b506831703ad3"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
