name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "617009d3d8db358432db9429167e328943ef397341742838dddc527781589c2d"

[versions]
fabric = "0.19.2"
minecraft = "1.21.11"
