name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8a7d5ccd7debad974fae8f919bc8f0e6a95f425bcfcb13c854f98001c424945a"

[versions]
fabric = "0.19.3"
minecraft = "1.21.11"
