name = "OneClient 1.21.11 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.11-fabric"
update-url = "oneclient/generated/hud-1.21.11-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "b26f130f8f541c4ac3f23b79d7c8bf2300fccc03c26abf9b3f66415970516680"

[versions]
fabric = "0.18.4"
minecraft = "1.21.11"
