name = "OneClient 1.21.5 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "Utility"
id = "utility-1.21.5-fabric"
update-url = "oneclient/generated/utility-1.21.5-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "89ed6157e67b46beb586da12a89d40ed02775b81ce4f55b371d0c175773a5048"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
