name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0f52a7ba51e4aa7cc41e4b6cad1c1ea1a26bee357b9d6c36e26b569ec3463cc1"

[versions]
fabric = "0.19.2"
minecraft = "26.1"
