name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "61b1a8f5e9e63ef07897be6b8905d2568f1b74a78408f01603ca2438f4ec0462"

[versions]
fabric = "0.19.3"
minecraft = "26.1"
