name = "OneClient 26.1 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.1-fabric"
update-url = "oneclient/generated/skyblock-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "71da19db09063d4ecb9734fdbf8cbd2c12528ec4ad0f58ead1d08d3491b6951d"

[versions]
fabric = "0.19.2"
minecraft = "26.1"
