name = "OneClient 1.21.5 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.5-fabric"
update-url = "oneclient/generated/pvp-1.21.5-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "9663474c222e4c26b5ff3688fba18e39cb5ad0dddfc97f96c2a58671299f6fa8"

[versions]
fabric = "0.17.2"
minecraft = "1.21.5"
