name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "720794571b77fffa70d72d3d3753828bb1cd032e3cbc2d006f761a078db41183"

[versions]
fabric = "0.18.5"
minecraft = "26.1"

[options]
acceptable-game-versions = []
