name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "0cae0fb6353a9d21932b3126f7a26b3cb3d2e5ec9c998493ccf22502abc65cd4"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
acceptable-game-versions = []
