name = "OneClient 26.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-26.1-fabric"
update-url = "oneclient/generated/qol-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5464a199f6d7ee82f4005008b23aa020bdd891ee318558f2218e87f1cd7bc7ed"

[versions]
fabric = "0.19.2"
minecraft = "26.1"

[options]
acceptable-game-versions = []
