name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "44deeb8f9c8e8f9e5766ae4614d5e734b5a7e37dfae8f44cb5b11fef01180e9f"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
