name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "e397f863cec1f9bb6d6c394bcbc6c33477d5b31cc0d6c86b026de657ba8b072d"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
