name = "OneClient 1.21.1 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.1-fabric"
update-url = "oneclient/generated/pvp-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "15585fc963e87a2242701949ee5e8892e64021f72b2a854ff8170dd9a5aa883d"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
