name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f9c14790af1630f52f7414b5f1d8c655ed6d58a4faad116ab85c10c24e6db493"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
