name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5645009e4f5e8e4dfc6092f47653cec07bb0fa67444da68d89339d41f5a9cf78"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
