name = "OneClient 1.21.10 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.10-fabric"
update-url = "oneclient/generated/qol-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c122c007301224505663f438399c8f189e5f3e944ce48d16462efa6317e5ccae"

[versions]
fabric = "0.18.5"
minecraft = "1.21.10"
