name = "OneClient 1.21.10 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.10-fabric"
update-url = "oneclient/generated/hud-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "cf93d6f05cd3950b9745c1a68618a50beb095344f45f92adb3beb0bf16cdf340"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
