name = "OneClient 1.21.10 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.10-fabric"
update-url = "oneclient/generated/hud-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "c47827e9b8a671a5dfc0aad204d22d1aa604b619ae8b67bf514537ae5d42770c"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
