name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "51536c88f69fd39d086f3e3b0fc8f1162120bfe807f5639b81d42160dc98248a"

[versions]
fabric = "0.19.3"
minecraft = "26.1"
