name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "d2aacd3f9d2a4e23f5375c1f0bc34d16d5c17abb6a4018061a8b5019d348aeab"

[versions]
fabric = "0.18.4"
minecraft = "26.1"
