name = "OneClient 26.1 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-26.1-fabric"
update-url = "oneclient/generated/utility-26.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f51c5e72cf5097a3ba2269d3e9f671bf3ad7a00321a80a7bc3846e453b57b272"

[versions]
fabric = "0.19.2"
minecraft = "26.1"
