name = "OneClient 26.2 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.2-fabric"
update-url = "oneclient/generated/skyblock-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "82ba403b4ec9f14b2668c29625e430159d7f01b532a1f65d657d54615e7862fe"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
