name = "OneClient 26.2 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.2-fabric"
update-url = "oneclient/generated/skyblock-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "964976b051d64d9d39544a8515f34b03cf8f9c93aa07e00d4114a7f309d68142"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
