name = "OneClient 26.2 Fabric [SkyBlock]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "SkyBlock"
id = "skyblock-26.2-fabric"
update-url = "oneclient/generated/skyblock-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "97c64a290d7b799ea0a858d8e4a0ed11858dd79c5b42a348757c468f2496952e"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
