name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "5fb2374de059fe33f3fcf1c0987da699abd6bd78f7347220a3c1da8de8d70132"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
