name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "bf562b89ed9d0f9d4d39cab0abeb4b4df9b873138e9c4ed9c51747bef8b4220f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.1"
