name = "OneClient 1.21.1 Fabric [QoL]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "QoL"
id = "qol-1.21.1-fabric"
update-url = "oneclient/generated/qol-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "894f3f235f9a4f2e034d76d84a37100a6560e109aec9e081deac74c351ee07d7"

[versions]
fabric = "0.19.3"
minecraft = "1.21.1"
