name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3893985cbf3680fa758d7e80341fa4b76a31c8e70f6a0b59fb9953d5198f11e6"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
