name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "533f6097c161bbde5e283c380e1802e14532235151a1b292d17143552c55f905"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
