name = "OneClient 1.21.10 Fabric [Utility]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "Utility"
id = "utility-1.21.10-fabric"
update-url = "oneclient/generated/utility-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "4f1e4395d1b78956d2887c82acfa3cbf3c98646de207e04390561a3561f2fa9e"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
