name = "OneClient 1.21.10 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.10-fabric"
update-url = "oneclient/generated/pvp-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "eb16ca98465dc7c7a2272ca8d05ea94eda90ce771b28e2c435a1ba6afb10555a"

[versions]
fabric = "0.19.2"
minecraft = "1.21.10"
