name = "OneClient 1.21.10 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.10-fabric"
update-url = "oneclient/generated/pvp-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "23a3c3dcd00a24b793f982df8a4110639feaf85228f93d9b25c908ba963ce83f"

[versions]
fabric = "0.18.4"
minecraft = "1.21.10"
