name = "OneClient 1.21.10 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-1.21.10-fabric"
update-url = "oneclient/generated/pvp-1.21.10-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "8007edd5c59d517cc840d026a460c9c3865f585323ce2b1a4920cdb9841370f3"

[versions]
fabric = "0.19.3"
minecraft = "1.21.10"
