name = "OneClient 1.21.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.1-fabric"
update-url = "oneclient/generated/hud-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "87f6c243b59d7f299cb07738420044a6c771300138ca87000fd3fcba09401777"

[versions]
fabric = "0.18.5"
minecraft = "1.21.1"
