name = "OneClient 1.21.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.1-fabric"
update-url = "oneclient/generated/hud-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "3bf2e68f0b8beaf3c4026177041d96d343159192634135c5e351e054e0b03182"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
