name = "OneClient 1.21.1 Fabric [HUD]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = true
category = "HUD"
id = "hud-1.21.1-fabric"
update-url = "oneclient/generated/hud-1.21.1-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "157bfdc1deaad0057e3656d3aff39b064e874c34b74881bc7ebdeacdcf6f633f"

[versions]
fabric = "0.19.2"
minecraft = "1.21.1"
