name = "OneClient 26.2 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.2-fabric"
update-url = "oneclient/generated/pvp-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "313da16240cc107805401f7f308942cf22151eda60014985305fe576567e6fee"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
