name = "OneClient 26.2 Fabric [PvP]"
author = "Polyfrost"
version = "1.0.0"
pack-format = "packwiz:1.1.0"
poly-format = "1"
enabled = false
category = "PvP"
id = "pvp-26.2-fabric"
update-url = "oneclient/generated/pvp-26.2-fabric.mrpack"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "2f19127e14e1074cf999746bea3a02afe7e8e771bb645657e8b7cc8d62c067f2"

[versions]
fabric = "0.19.3"
minecraft = "26.2"
